const express = require('express');
const cors = require('cors');

const app = express();
app.use(cors());
app.use(express.json());

const ROOT = {
  breadcrumb: "Cluster",
  aggregatedBy: "Cluster",
  bars: [
    { label: "Cluster A", height: 100 },
    { label: "Cluster B", height: 81 },
    { label: "Cluster C", height: 68 },
    { label: "Cluster D", height: 37 },
  ],
  rows: [
    {
      name: "Cluster A",
      cpu: "$2,463",
      ram: "$1,368",
      storage: "$246",
      net: "$307",
      gpu: "$821",
      eff: "10%",
      total: "$6,867",
    },
    {
      name: "Cluster B",
      cpu: "$2,127",
      ram: "$1,181",
      storage: "$212",
      net: "$265",
      gpu: "$0",
      eff: "28%",
      total: "$5,574",
    },
    {
      name: "Cluster C",
      cpu: "$1,733",
      ram: "$962",
      storage: "$173",
      net: "$216",
      gpu: "$577",
      eff: "15%",
      total: "$4,664",
    },
    {
      name: "Cluster D",
      cpu: "$1,218",
      ram: "$677",
      storage: "$121",
      net: "$152",
      gpu: "$0",
      eff: "50%",
      total: "$2,545",
    },
  ],
  children: [
    // Cluster A → Namespaces
    {
      breadcrumb: "Cluster A - Namespace",
      aggregatedBy: "Namespace",
      bars: [
        { label: "Namespace A", height: 100 },
        { label: "Namespace B", height: 77 },
        { label: "Namespace C", height: 60 },
        { label: "Namespace D", height: 20 },
      ],
      rows: [
        {
          name: "Namespace A",
          cpu: "$1,231",
          ram: "$684",
          storage: "$123",
          net: "$153",
          gpu: "$410",
          eff: "5%",
          total: "$3,433",
        },
        {
          name: "Namespace B",
          cpu: "$739",
          ram: "$410",
          storage: "$73",
          net: "$92",
          gpu: "$246",
          eff: "20%",
          total: "$2,060",
        },
        {
          name: "Namespace C",
          cpu: "$369",
          ram: "$205",
          storage: "$36",
          net: "$46",
          gpu: "$123",
          eff: "50%",
          total: "$1,030",
        },
        {
          name: "Namespace D",
          cpu: "$123",
          ram: "$68",
          storage: "$12",
          net: "$15",
          gpu: "$41",
          eff: "40%",
          total: "$343",
        },
      ],
      children: [
        // Namespace A → Pods
        {
          breadcrumb: "Cluster A - Namespace A - Pods",
          aggregatedBy: "Pod",
          bars: [
            { label: "Pod A", height: 100 },
            { label: "Pod B", height: 29 },
            { label: "Pod C", height: 18 },
            { label: "Pod D", height: 11 },
          ],
          rows: [
            {
              name: "Pod A",
              cpu: "$862",
              ram: "$479",
              storage: "$86",
              net: "$107",
              gpu: "$410",
              eff: "8%",
              total: "$2,403",
            },
            {
              name: "Pod B",
              cpu: "$246",
              ram: "$136",
              storage: "$24",
              net: "$30",
              gpu: "$246",
              eff: "40%",
              total: "$686",
            },
            {
              name: "Pod C",
              cpu: "$86",
              ram: "$47",
              storage: "$8",
              net: "$10",
              gpu: "$123",
              eff: "35%",
              total: "$240",
            },
            {
              name: "Pod D",
              cpu: "$36",
              ram: "$20",
              storage: "$3",
              net: "$60",
              gpu: "$41",
              eff: "70%",
              total: "$103",
            },
          ],
          children: [null, null, null, null],
        },
        null,
        null,
        null,
      ],
    },
    // Cluster B → Namespaces
    {
      breadcrumb: "Cluster B - Namespace",
      aggregatedBy: "Namespace",
      bars: [
        { label: "Namespace A", height: 100 },
        { label: "Namespace B", height: 60 },
        { label: "Namespace C", height: 40 },
        { label: "Namespace D", height: 15 },
      ],
      rows: [
        {
          name: "Namespace A",
          cpu: "$1,050",
          ram: "$583",
          storage: "$105",
          net: "$131",
          gpu: "$0",
          eff: "12%",
          total: "$2,938",
        },
        {
          name: "Namespace B",
          cpu: "$631",
          ram: "$350",
          storage: "$63",
          net: "$79",
          gpu: "$0",
          eff: "35%",
          total: "$1,759",
        },
        {
          name: "Namespace C",
          cpu: "$315",
          ram: "$175",
          storage: "$31",
          net: "$39",
          gpu: "$0",
          eff: "52%",
          total: "$878",
        },
        {
          name: "Namespace D",
          cpu: "$50",
          ram: "$28",
          storage: "$5",
          net: "$6",
          gpu: "$0",
          eff: "75%",
          total: "$105",
        },
      ],
      children: [null, null, null, null],
    },
    // Cluster C → Namespaces
    {
      breadcrumb: "Cluster C - Namespace",
      aggregatedBy: "Namespace",
      bars: [
        { label: "Namespace A", height: 100 },
        { label: "Namespace B", height: 55 },
        { label: "Namespace C", height: 30 },
        { label: "Namespace D", height: 10 },
      ],
      rows: [
        {
          name: "Namespace A",
          cpu: "$866",
          ram: "$481",
          storage: "$86",
          net: "$108",
          gpu: "$288",
          eff: "8%",
          total: "$2,332",
        },
        {
          name: "Namespace B",
          cpu: "$519",
          ram: "$288",
          storage: "$52",
          net: "$65",
          gpu: "$173",
          eff: "22%",
          total: "$1,399",
        },
        {
          name: "Namespace C",
          cpu: "$260",
          ram: "$144",
          storage: "$26",
          net: "$32",
          gpu: "$86",
          eff: "45%",
          total: "$700",
        },
        {
          name: "Namespace D",
          cpu: "$86",
          ram: "$48",
          storage: "$9",
          net: "$11",
          gpu: "$29",
          eff: "55%",
          total: "$233",
        },
      ],
      children: [null, null, null, null],
    },
    // Cluster D → Namespaces
    {
      breadcrumb: "Cluster D - Namespace",
      aggregatedBy: "Namespace",
      bars: [
        { label: "Namespace A", height: 100 },
        { label: "Namespace B", height: 50 },
        { label: "Namespace C", height: 25 },
        { label: "Namespace D", height: 8 },
      ],
      rows: [
        {
          name: "Namespace A",
          cpu: "$609",
          ram: "$338",
          storage: "$60",
          net: "$76",
          gpu: "$0",
          eff: "25%",
          total: "$1,272",
        },
        {
          name: "Namespace B",
          cpu: "$304",
          ram: "$169",
          storage: "$30",
          net: "$38",
          gpu: "$0",
          eff: "55%",
          total: "$636",
        },
        {
          name: "Namespace C",
          cpu: "$152",
          ram: "$84",
          storage: "$15",
          net: "$19",
          gpu: "$0",
          eff: "65%",
          total: "$318",
        },
        {
          name: "Namespace D",
          cpu: "$50",
          ram: "$28",
          storage: "$5",
          net: "$6",
          gpu: "$0",
          eff: "75%",
          total: "$105",
        },
      ],
      children: [null, null, null, null],
    },
  ],
};

app.get('/api/cluster-drilldown', (req, res) => {
  res.json(ROOT);
});

app.listen(5000, () => {
  console.log('🚀 Backend running on http://localhost:5000');
});